version: "3"

volumes:
  tasks_local_postgres_data: {}
  tasks_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tasks_local_django
    container_name: tasks_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
      - rabbitmq
    volumes:
      - .:/app:z

    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tasks_production_postgres
    container_name: tasks_local_postgres
    volumes:
      - tasks_local_postgres_data:/var/lib/postgresql/data
      - tasks_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  postgres-hourly-backup:
    image: tasks_production_postgres
    depends_on:
      - postgres
    volumes:
      - ./.backup_1h:/.backup_1h
    command: >
      bash -c "while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h postgres -U $$POSTGRES_USER -Fc $$POSTGRES_DB > /.backup_1h/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /.backup_1h/*.dump | head -n -5 | xargs rm -f
        sleep 3600
      done"
    env_file:
      - ./.envs/.local/.postgres

  postgres-daily-backup:
    image: tasks_production_postgres
    depends_on:
      - postgres
    volumes:
      - ./.backup_24h:/.backup_24h
    command: >
      bash -c "while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h postgres -U $$POSTGRES_USER -Fc $$POSTGRES_DB > /.backup_24h/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /.backup_24h/*.dump | head -n -5 | xargs rm -f
        sleep 86400
      done"
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: tasks_local_docs
    container_name: tasks_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./app:/app/app:z
    ports:
      - "9500:9000"
    command: /start-docs

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: tasks_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: tasks_local_redis

  rabbitmq:
    image: docker.io/rabbitmq:3-management
    container_name: pet-shop_local_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  celeryworker:
    <<: *django
    image: tasks_local_celeryworker
    container_name: tasks_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
      - rabbitmq
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: tasks_local_celerybeat
    container_name: tasks_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
      - rabbitmq
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: tasks_local_flower
    container_name: tasks_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
