# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.django.test --reuse-db"
python_files = ["tests.py", "test_*.py"]
filterwarnings = [
  "ignore:::.*factory.django:181",
  "ignore:::.*ninja.orm.metaclass:90",
  "ignore:::.*pydantic._internal._config:272",
  "ignore:::.*django.core.handlers.base:61",
  "ignore:::.*pydantic._internal._config:291",
  "ignore:::.*pydantic.main:364",
]

# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']

# ==== flake8 ====
[tool.flake8]
max-line-length = 119

# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119
known_first_party = ["firebase", "config"]
skip = ["venv/"]
skip_glob = ["**/migrations/*.py"]

# ==== Coverage ====
[tool.coverage.run]
include = ["app/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]

# ==== mypy ====
[tool.mypy]
python_version = "3.11"
show_traceback = true
plugins = ["mypy_django_plugin.main"]
ignore_errors = true

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[[tool.mypy.overrides]]
# Django test should not produce any errors:
module = "*/tests/*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "app"
ignore_errors = true

[tool.djangorestframework-stubs]
django_settings_module = "app"
ignore_errors = true

# ==== PyLint ====
[tool.pylint.MASTER]
load-plugins = ["pylint_django"]
django-settings-module = "config.django.local"

[tool.pylint.FORMAT]
max-line-length = 119

[tool.pylint."MESSAGES CONTROL"]
disable = ["missing-docstring", "invalid-name"]

[tool.pylint.DESIGN]
max-parents = 13

[tool.pylint.TYPECHECK]
generated-members = [
  "REQUEST",
  "acl_users",
  "aq_parent",
  "[a-zA-Z]+_set{1,2}",
  "save",
  "delete",
]


# ==== djLint ====
[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
ignore = "H006,H030,H031,T002"
include = "H017,H035"
indent = 2
max_line_length = 119
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2
